[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$major.$minor.$patch"
version_scheme = "semver"
version_provider = "npm"
update_changelog_on_bump = true
changelog_incremental = true
major_version_zero = true
